### ISSUE TITLE
ELIXIR Toolkit Theme usage

### ISSUE THREAD

**Issue by bedroesb** [ResearchObject/ro-crate#306]
Hello, thanks a lot for using the ETT! I am the creator and just wanted to give my two cents on the usage of the theme.
Sorry if I bring up points that were already extensively discussed.

- [ ] #314
- [ ] #315
- [x] #316
- [ ] #317
- [ ] (Eli added via edit 2025-12-17) #344 

Feel free to open requests or feature pull requests in the original repo of the theme off course, I will be happy to review them. 

@stain I am more than happy to help out, since I helped setting up the previous theme of the RO crate website...

**Comment by elichad** [comment]
Hi @bedroesb I've migrated this issue to the central ro-crate repo as we've now rolled out the new website - but we will still discuss your suggestions as planned tomorrow and incorporate some changes

**Comment by PhilReedData** [comment]
This work supersedes https://github.com/ResearchObject/ro-crate/issues/306 as I am making the jump from 2.4.0 to 6.1.0 here, in branch https://github.com/ResearchObject/ro-crate/tree/ett-6.1.0 

So far, I have removed a lot of the custom .html files and some of the custom CSS. There is much more to do. 

My list so far, by template page and by feature.

### By page

`head.html`
  -  Removed for now. Our previous customisations were:
    - Add description from first 30 words (now part of ETT base?)
    - Hide future blog posts (include `hide-future-posts.js`)
    - Add RSS feed for blog (`blog.xml`) to head

`image.html` no change

`item_details, posts, realted_use_cases, tools-table.html`
  - These pages are unique to RO-Crate (should use hyphen not underscore).

`related-pages.html`
  - We simplified this from `div` to `ul`. I have left in the old override page for now.

`section-navigation-tiles-simple.html`
  - I have removed the override page for now, not clear what we customised here.

`section-navigation-tiles.html`
  - I have removed the override page. We previously customised to add images (from the `assets/img` folder, and some from the FontAwesome icons.
  - I have updated the `use_cases` files to use the `page_img` feature from ETT instead, and copied the relevant graphics to the path that ETT expects `images`. 
  - I have not yet updated the other types of tiles using the FA icons, will need to save these icons as SVG in the `images` folder, most likely (and add a README to describe the license used?).
  - We previously took out the FAIR Cookbook and DSW code. It did no harm.
  - We changed the sort order to `sort_natural`... would be good to add that back. Maybe we propose a flag in base ETT for this? (Eli edit: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/449)
  - We made some accessibility improvements to the search box... if these are good for everyone, we should put them as a PR in base ETT instead.     
  - I have not cleared out all the old CSS here yet. It doesn't seem to have broken much. I added some new CSS to hide the tile type (like I did on FAIRDOM), again, would be a good option for everyone as a PR. 

`sidebar.html`
- This has major changes, and we had major customisations.
- I have deleted our override page for now but will surely need to add a new one. We use custom menus in several ways:
  - Blog: populate with recent blog post title and link
  - Specification: populate with subheadings from spec pages
  - Main: populate with use cases, domains, tasks, roles
- I am not sure how the last one works. I think best to customise as little code as possible in a new `sidebar.html` and link out to a separate html file with as much of the custom work as possible. Perhaps pick up when one of the 'special' sidebars is used, and do that work in another file. 
-  Or do we need to change the sidebar yaml files instead, dynamically?

`topnav.html`
- I have removed the override page, since the latest has new features (more socials, skip to aside, more classes in nav).
- The feature we most used was to hide the site name as text. I now use CSS for this instead.

`_sass/*.scss`
- I have removed code that I saw was causing problems. There is more to clear here. 
- I added a few new bits as described above. 

`_layouts`
- I deleted the `default` layout.
- That caused the pages to load without the `main` element, so the layout went strange, applying a grid to everything after the sidebar. 
- By changing everything except the blog pages to use `page` layout instead of `default`, that fixed the layout. It introduced a new problem of showing two different `<h1>` on every page. 
- I need some help here.

**Comment by PhilReedData** [comment]
Overriding `section-navigation-tiles.html` is necessary to add all features, including the drop-down button of related pages which I missed before. I have added that back in, and added back the custom code to use FA icons on domains, tasks and roles. <img width="1545" height="1239" alt="Image" src="https://github.com/user-attachments/assets/f191cfab-98f7-4cd8-96fe-05e378f1a51b" />

**Comment by PhilReedData** [comment]
I'm getting there but there is much to do.

<img width="1544" height="1040" alt="Image" src="https://github.com/user-attachments/assets/0068fde7-8065-45de-8537-edfc85d92a5f" />

Functionally working:

- [x] All sidebars show all pages: main (use cases submenus), blog (latest posts), spec (versions), the rest
- [x] Main navigation working
- [x] Pages all load a `<main>` element, grid layout is functioning

Unfinished:
- [ ] The layouts are still off, duplicating the `<h1>` and the related pages sections. (I'm trying not to override the `layouts` pages but might have to.)
- [ ] On use cases etc pages: Main sidebar does not understand active submenus, so the buttons are collapsed (the four top level pages work fine.
- [ ] The Tools table has a gap on the right side, like it wants to leave room for a table of contents which is disabled.
- [ ] The blog sidebar still shows the XML/RSS page at the top.
- [ ] The future blog posts are likely not hidden. (untested)
- [ ]  The sidebar theme is mostly default ETT, it does not have the side border for active page like before. 
- [ ] The spacing of the icons on the top pages for Domains, Tasks, Roles is a little bit off. 
- [ ] Various accessibility tweaks that were custom overrides to ETT pages have not been ported back.
- [ ] Mobile view is not tested. 

After working 2.5 days on this, I need to step away to get back to other tasks.

**Comment by PhilReedData** [comment]
Progress today (3 hours):

- [x] The layouts are still off, duplicating the `<h1>` and the related pages sections. (I'm trying not to override the `layouts` pages but might have to.)
  - [x] Most pages now have the #315 use of `title:` instead of H1 implemented.
  - [x] The exception is the index pages for the specifications, as they read this from `_metadata.liquid`; I don't want to break the specifications make scripts that build the JSON/JSON-LD releases, so I want to hand this part over to someone who understands it. [Eli edit: #567 resolves this]
  - [x] The specification index pages are supposed to include `references.liquid` but these do not load, I don't know why. [Eli edit: resolved; they're just Markdown references, nothing should be displayed]
- [ ] On use cases etc pages: Main sidebar does not understand active submenus, so the buttons are collapsed (the four top level pages work fine.
  - [ ] I've investigated this further, there is a bug in my sidebar code which spits out too many `</li>` that doesn't seem to break anything. I also found a bug in the ETT sidebar file and reported it https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/issues/437 -- so I think some more work required here, perhaps start again? This is the most time consuming and difficult part. 
- [ ] The Tools table has a gap on the right side, like it wants to leave room for a table of contents which is disabled.
  - [ ] For some reason, the latest ETT will load additional `<colgroup>` into the table header, making it think there are six columns instead of three. We could delete the three we set out in `_includes/toolstable.html` but then the column widths would change between pages. I couldn't see any mention of colgroup in the ETT repo (code nor discussion). [Eli edit: see suggestions in #545 ]
- [ ] The blog sidebar still shows the XML/RSS page at the top.
- [ ] The future blog posts are likely not hidden. (untested)
- [ ]  The sidebar theme is mostly default ETT, it does not have the left-side border for active page like before. 
- [ ] The spacing of the icons on the top pages for Domains, Tasks, Roles is a little bit off. 
- [ ] Various accessibility tweaks that were custom overrides to ETT pages have not been ported back.
- [ ] Mobile view is not tested. 
- [x] The word-break style for hyperlinks was added in latest ETT, which made the table on the `whats-changed-in-1-3` page load badly. I have reversed this with CSS, the original 'normal' behaviour applies for links in tables.

**Comment by PhilReedData** [comment]
Latest:

- There is the 'primary' branch `ett-6.1.0` with most of my work so far, the features that are agreed or uncontroversial. 
  - [x] This now includes the use case, tasks, domains and roles pages manually entered into the `main.yml` sidebar, and updated instructions in the use case README. 
  - [x] My CSS code to hide the page type in the navigation tiles is removed. You now see 'use case' with each use case tile, but usefully you now see 'task' or 'role' for each tile of the related pages for domains.
  - [x] I removed the related pages call in the domains, since it happens already in the page layout.
- There is now the first of several sub-branches `ett-6.1.0-sidebar` which contains some custom sidebar code for the blog posts 
  - [ ] We could improve this code (exclude the RSS feed first item, remove the redundant empty `date` parameter used in non-blog post sidebars. Or we could abandon this branch and manually include the blog posts in the `blog.yml` sidebar. 
  - [ ] I haven't done anything else about hiding future posts.
  - [ ] (Eli edit) Eli suggests: to exclude the RSS feed, add `type: none` to RSS feed front matter, then filter for `type: blog_posts` when building sidebar
  - Bert has invited us to implement a blog feature upstream to ETT. (Eli edit: draft PR in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/447)
- [ ] The Tools table still shows the extra space on the right because it still adds an extra `colgroup` element dynamically.
- [x] The specification index pages now include the contents correctly. 
- [ ] Previous comment describes a few more outstanding ideas.

We can work through the crucial items to get the site working and in production, then start on the upstream changes and implementing features beyond ETT 6.1.0. These include:

- Upstream contributions:
  - Tools table: adapted from the tools and resources table in ETT (needs to have Status column added, for example).
  - Domains/roles/tasks: switch to the new Lucide icons instead of FontAwesome, work like the page_img feature.
  - Blog
- RO-Crate specific:
  - Use new Lucide icons in sidebar for use cases, domains, roles, tasks (and update the home page to match)
  - Make the domains/roles/tasks more obvious on the use case index page (reuse the front page graphics somehow, with new Lucide icons)

Sorry these are not all captured as sub-issues yet. To be discussed further. I am out of time on this work now, perhaps for a few weeks. Happy for @elichad to pick up from here.

**Comment by elichad** [comment]
> Most pages now have the #315 use of title: instead of H1 implemented.

In the specification pages this causes an issue - when we build other versions of the spec with the `Makefile`, the raw markdown files are used, ignoring the front matter. So having no h1 directly in the Markdown means the chapter titles are missing in the output.

@bedroesb is it possible to disable the `title` front matter being rendered as an `h1` on some pages?

**Comment by bedroesb** [comment]
Yes, by not setting it :) but than you lose the 'edit me' buttons

**Comment by elichad** [comment]
removing `title` also has some consequences for the `<head>` metadata / preview text so I'm not keen on it as a solution!

having had a quick look at the ETT code, I think the best way forward is just to hide the extra title in our custom CSS:
```
#content h1 {
    display: none;
}
```
and make a note of it somewhere.

**Comment by bedroesb** [comment]
hmmm do know that that css rule will be applied to all pages, try to target only the pages of the specification so you can use the themes way of setting titles on the other pages.

**Comment by elichad** [comment]
Phil did already update our branch to use `title` on all the other pages of the website - the CSS above only hides h1s in the Markdown content (the Markdown headings are what I meant by the "extra title" in the previous comment, just realized that wasn't clear).

It feels a little fragile though so I also wrote some tests in #567 to ensure the title is set properly on all pages: [5d0e5420fecaffe75d7e6fe7160fbad66375e5bf](https://github.com/ResearchObject/ro-crate/pull/567/changes/5d0e5420fecaffe75d7e6fe7160fbad66375e5bf). (These build on our existing use of [html-proofer](https://github.com/gjtorikian/html-proofer) in our [CI workflow](https://github.com/ResearchObject/ro-crate/blob/main/.github/workflows/test.yml))
