### ISSUE TITLE
Review RO-Crate 1.1-DRAFT new sections

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#97]
Following discussion in call [2020-09-24](https://s.apache.org/ro-crate-minutes#heading=h.wf9ll2ymr0qu) we will review [RO-Crate 1.1-DRAFT](https://www.researchobject.org/ro-crate/1.1-DRAFT/#table-of-contents) until Thurs 2020-10-01, as we have added new sections that have not been proofread yet.

After review we aim to release 1.1 on Fri 2020-10-02.

From [Changelog](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/changelog.html):

  * **Note**: The RO-Crate metadata file is renamed to `ro-crate-metadata.json` to facilitate use of JSON editors.  [#82](https://github.com/ResearchObject/ro-crate/issues/82) [#84](https://github.com/ResearchObject/ro-crate/issues/84)
  * [Data entities](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/data-entities.md) can reference external resources with absolute URI [#74](https://github.com/ResearchObject/ro-crate/issues/74)
  * Added section on considerations for [Web-based Data Entities](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/data-entities.md#web-based-data-entities)  [#74](https://github.com/ResearchObject/ro-crate/issues/74)
  * The [root dataset](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/root-data-entity.md#direct-properties-of-the-root-data-entity) is no longer required to be `./` [#74](https://github.com/ResearchObject/ro-crate/issues/74)
  * [RO-Crate Root](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/structure.md) directory no longer requires payload files [#74](https://github.com/ResearchObject/ro-crate/issues/74)
  * [Workflows and scripts](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/workflows.md) section now aligned with [BioSchemas ComputationalWorkflow profile](https://bioschemas.org/profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21/)  [#81](https://github.com/ResearchObject/ro-crate/issues/81)
  * Added section [Programming with JSON-LD](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/appendix/implementation_notes.md#programming-with-json-ld) and note that `@type` might be an array [#85](https://github.com/ResearchObject/ro-crate/issues/85)
  * Added new section [Handling relative URI references](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/appendix/jsonld.md#handling-relative-uri-references) [#73](https://github.com/ResearchObject/ro-crate/issues/73)
  * JSON-LD context no longer sets `@base: null` [#73](https://github.com/ResearchObject/ro-crate/issues/73)
  * Added note on [Encoding file paths](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/data-entities.md#encoding-file-paths) [#77](https://github.com/ResearchObject/ro-crate/issues/77) [#80](https://github.com/ResearchObject/ro-crate/issues/80)
  * Added section [Choosing URLs for ad hoc terms](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/appendix/jsonld.md#adding-new-or-ad-hoc-vocabulary-terms) [#71](https://github.com/ResearchObject/ro-crate/issues/71) [#90](https://github.com/ResearchObject/ro-crate/issues/90)
  * Section [RO-Crate JSON-LD Media type](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT/appendix/jsonld.md#ro-crate-json-ld-media-type) expanded to suggest HTTP server configuration
  * Update JSON-LD context to [schema.org 10.0](http://schema.org/version/10.0/)
  * Remove HTML use of `relatedLink` property in [RepositoryCollection example](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT//provenance.md#digital-library-and-repository-content) [#91](https://github.com/ResearchObject/ro-crate/pull/91)
  * Distinguish between [contextual/data entities](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT//contextual-entities.md#contextual-vs-data-entities) [#94](https://github.com/ResearchObject/ro-crate/pull/94)
  * Change theme to `jekyll-rtd-theme` and split into multiple pages [#95](https://github.com/ResearchObject/ro-crate/pull/95)

I merged #95 so you can navigate and edit the split files either from above or from https://www.researchobject.org/ro-crate/1.1-DRAFT/ - but note that "1.1-DRAFT" is missing from the left-hand menu before it is released. See [Table of contents](https://www.researchobject.org/ro-crate/1.1-DRAFT/#table-of-contents) instead.

Volunteers per section:

- [x] @dgarijo: [Ad-Hoc vocabularies](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html?highlight=ad-hoc#adding-new-or-ad-hoc-vocabulary-terms)
- [x] @dgarijo: [Programming with JSON-LD](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/implementation_notes.html#programming-with-json-ld)
- [x] @dgarijo: [HTTP server configuration](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html#ro-crate-json-ld-media-type)
- [x] @dgarijo: ([Workflows and scripts](https://www.researchobject.org/ro-crate/1.1-DRAFT/workflows.html)) - see also #100
- [x] @nsjuty: [Workflows and scripts](https://www.researchobject.org/ro-crate/1.1-DRAFT/workflows.html)
- [x] @nsjuty: [Encoding file paths](https://www.researchobject.org/ro-crate/1.1-DRAFT/data-entities.html#encoding-file-paths)
- [x] @ptsefton: [Contextual vs Data Entities](https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT//contextual-entities.md#contextual-vs-data-entities) #94 
- [x] @ljgarcia: [Handling relative URI references](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html#handling-relative-uri-references)
- [x] @ljgarcia: [Web-based Data Entities](https://www.researchobject.org/ro-crate/1.1-DRAFT/data-entities.html#web-based-data-entities)
- [ ] @alaninmcr [Workflows and scripts](https://www.researchobject.org/ro-crate/1.1-DRAFT/workflows.html) changes in #100

**Deadline**: Thurs 2020-10-01

Either comment on this issue or make pull request/issue for changes.

**Comment by stain** [comment]
@dgarijo or @ljgarcia, are either of you able to also check out [HTTP server configuration](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html#ro-crate-json-ld-media-type)?  At least the English, I tested each of the configs.

@nsjuty I added [Encoding file paths](https://www.researchobject.org/ro-crate/1.1-DRAFT/data-entities.html#encoding-file-paths) as well.

@ljgarcia I added [Web-based Data Entities](https://www.researchobject.org/ro-crate/1.1-DRAFT/data-entities.html#web-based-data-entities) as it's also about URI/identifiers.

**Comment by stain** [comment]
Also **TODO** for myself (or a volunteer that knows make/pandoc):

[ ] **@stain**: Update [Makefile](https://github.com/ResearchObject/ro-crate/blob/master/Makefile) to concatenate *.md in correct order
[ ] **@stain**: Ensure concatenated HTML has correct internal `#internal` links or do a clever `sed`
[ ] **@stain**: Make html/pdf for Zenodo (if above not possible, *zip of htmls)

**Comment by stain** [comment]
For Friday: 
- [ ] @CaroleGoble and @stain: Draft press release (also add to Bioschemas website)

**Comment by alaninmcr** [comment]
To comply with the  BioSchemas ComputationalWorkflow profile, the data entities **MUST** have the listed properties.

Better stated as:  the data entities **SHOULD** comply with the  BioSchemas ComputationalWorkflow profile. To comply with the profile, the data entities **MUST** ...

For FormalParameter, the data entities **MUST** describe the properties name, additionalType and encodingFormat.

**Comment by stain** [comment]
@alaninmcr if we are listing the MUSTs from the BioSchemas profiles then presumably we should also list the SHOULDs? 

See [my attempt](https://github.com/ResearchObject/ro-crate/pull/100/files?short_path=b28b5da#diff-b28b5dab908e4a01e00983d24ea3aa96) in #100 - I am not sure about this as it gets a bit big and scary and people might think "Oh I won't do workflows then"

**Comment by stain** [comment]
Thanks @nsjuty - merged #101 #102

**Comment by stain** [comment]
The so-called "clever sed" (bfd9b2f53075f464b069b017c9648460879dda94) actually worked and I fixed `Makefile` to make the Zenodo PDF again.

Preview of concatenated PDF: <https://www.dropbox.com/s/4mtrw4xj4mz9xav/ro-crate-1.1.0-RC1.pdf?dl=0>

**Comment by ljgarcia** [comment]
* [Handling relative URI references](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html#handling-relative-uri-references) review done, [PR 104](https://github.com/ResearchObject/ro-crate/pull/104) created
* [Web-based Data Entities](https://www.researchobject.org/ro-crate/1.1-DRAFT/data-entities.html#web-based-data-entities) review done, [PR 103](https://github.com/ResearchObject/ro-crate/pull/103) created

**Comment by dgarijo** [comment]
Summary of my changes:
- @stain I went through https://github.com/ResearchObject/ro-crate/pull/100 and left a review there. 
- I did a pull request with my review https://github.com/ResearchObject/ro-crate/pull/105 (not many changes were required, I also made sure that the examples using the new ro-terms ns are resolvable).
